[versions]
# libraries
junit = "5.10.1"
opentest4j = "1.3.0"

# plugins
kotlin = "2.1.0"
intelliJPlatform = "2.2.1"
changelog = "2.2.1"
qodana = "2024.2.3"
kover = "0.8.3"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }